name: Manual Run with Summary

on:
  workflow_dispatch:

jobs:
  build-and-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Node version before setup
        run: node --version

      - name: Current date
        run: date

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node version after setup
        run: node --version
